# Generated by Django 4.2.1 on 2025-03-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_published',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
