# Generated by Django 4.2.1 on 2025-04-20 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_tagpost_alter_menu_cat_menu_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuGalleryCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_covers/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('menu', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover', to='menu.menu')),
            ],
        ),
    ]
