# Generated by Django 4.2.1 on 2025-04-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menugallerycover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menugallerycover',
            name='image',
            field=models.ImageField(upload_to='menu/news_covers/'),
        ),
    ]
